// Shared country utilities — eliminates duplication across dashboard, rent, numbers pages

export const countryCallingCodes: Record<string, string> = {
  usa: '+1',
  canada: '+1',
  russia: '+7',
  kazakhstan: '+7',
  egypt: '+20',
  southafrica: '+27',
  greece: '+30',
  netherlands: '+31',
  belgium: '+32',
  france: '+33',
  spain: '+34',
  hungary: '+36',
  italy: '+39',
  romania: '+40',
  switzerland: '+41',
  austria: '+43',
  england: '+44',
  unitedkingdom: '+44',
  denmark: '+45',
  sweden: '+46',
  norway: '+47',
  poland: '+48',
  germany: '+49',
  peru: '+51',
  mexico: '+52',
  cuba: '+53',
  argentina: '+54',
  brazil: '+55',
  chile: '+56',
  colombia: '+57',
  venezuela: '+58',
  malaysia: '+60',
  australia: '+61',
  indonesia: '+62',
  philippines: '+63',
  newzealand: '+64',
  singapore: '+65',
  thailand: '+66',
  japan: '+81',
  vietnam: '+84',
  china: '+86',
  turkey: '+90',
  india: '+91',
  pakistan: '+92',
  afghanistan: '+93',
  srilanka: '+94',
  myanmar: '+95',
  iran: '+98',
  morocco: '+212',
  algeria: '+213',
  tunisia: '+216',
  libya: '+218',
  senegal: '+221',
  ivorycoast: '+225',
  ghana: '+233',
  nigeria: '+234',
  kenya: '+254',
  israel: '+972',
  saudiarabia: '+966',
  iraq: '+964',
  unitedarabemirates: '+971',
  jordan: '+962',
  syria: '+963',
  lebanon: '+961',
  kuwait: '+965',
  saudi: '+966',
  yemen: '+967',
  oman: '+968',
  palestine: '+970',
  qatar: '+974',
  bahrain: '+973',
  mongolia: '+976',
  nepal: '+977',
  tajikistan: '+992',
  turkmenistan: '+993',
  azerbaijan: '+994',
  georgia: '+995',
  kyrgyzstan: '+996',
  uzbekistan: '+998'
};

const countryNameTranslations: Record<string, Record<string, string>> = {
  tr: {
    usa: "Amerika", canada: "Kanada", russia: "Rusya", kazakhstan: "Kazakistan", egypt: "Mısır",
    southafrica: "Güney Afrika", greece: "Yunanistan", netherlands: "Hollanda", belgium: "Belçika", france: "Fransa",
    spain: "İspanya", hungary: "Macaristan", italy: "İtalya", romania: "Romanya", switzerland: "İsveçre",
    austria: "Avusturya", england: "İngiltere", unitedkingdom: "Birleşik Krallık", denmark: "Danimarka",
    sweden: "İsveç", norway: "Norveç", poland: "Polonya", germany: "Almanya", turkey: "Türkiye", india: "Hindistan",
    azerbaijan: "Azerbaycan", georgia: "Gürcistan", kyrgyzstan: "Kırgızistan", uzbekistan: "Özbekistan",
    colombia: "Kolombiya", brazil: "Brezilya", indonesia: "Endonezya", ukraine: "Ukrayna", vietnam: "Vietnam",
    thailand: "Tayland", philippines: "Filipinler"
  },
  en: {
    usa: "United States", canada: "Canada", russia: "Russia", kazakhstan: "Kazakhstan", egypt: "Egypt",
    southafrica: "South Africa", greece: "Greece", netherlands: "Netherlands", belgium: "Belgium", france: "France",
    spain: "Spain", hungary: "Hungary", italy: "Italy", romania: "Romania", switzerland: "Switzerland",
    austria: "Austria", england: "England", unitedkingdom: "United Kingdom", denmark: "Denmark",
    sweden: "Sweden", norway: "Norway", poland: "Poland", germany: "Germany", turkey: "Turkey", india: "India",
    azerbaijan: "Azerbaijan", georgia: "Georgia", kyrgyzstan: "Kyrgyzstan", uzbekistan: "Uzbekistan",
    colombia: "Colombia", brazil: "Brazil", indonesia: "Indonesia", ukraine: "Ukraine", vietnam: "Vietnam",
    thailand: "Thailand", philippines: "Philippines"
  },
  az: {
    usa: "Amerika Birləşmiş Ştatları", canada: "Kanada", russia: "Rusiya", kazakhstan: "Qazaxıstan", egypt: "Misir",
    southafrica: "Cənubi Afrika", greece: "Yunanıstan", netherlands: "Niderland", belgium: "Belçika", france: "Fransa",
    spain: "İspaniya", hungary: "Macarıstan", italy: "İtaliya", romania: "Rumıniya", switzerland: "İsveçrə",
    austria: "Avstriya", england: "İngiltərə", unitedkingdom: "Birləşmiş Krallıq", denmark: "Danimarka",
    sweden: "İsveç", norway: "Norveç", poland: "Polşa", germany: "Almaniya", turkey: "Türkiyə", india: "Hindistan",
    azerbaijan: "Azərbaycan", georgia: "Gürcüstan", kyrgyzstan: "Qırğızıstan", uzbekistan: "Özbəkistan",
    colombia: "Kolumbiya", brazil: "Braziliya", indonesia: "İndoneziya", ukraine: "Ukrayna", vietnam: "Vyetnam",
    thailand: "Tayland", philippines: "Filippin"
  }
};

export function getCountryName(countryCode: string, defaultName: string, language: string): string {
  const code = countryCode.toLowerCase().replace(/[^a-z]/g, '');
  return countryNameTranslations[language]?.[code] || defaultName;
}
