"use client";

import { useState } from 'react';

// Hardcoded app icon mapping for fallback styling
export const appIconMap: Record<string, { icon: string, color: string }> = {
  'whatsapp': { icon: 'W', color: 'text-emerald-500 bg-emerald-50 border-emerald-100' },
  'telegram': { icon: 'T', color: 'text-sky-500 bg-sky-50 border-sky-100' },
  'google': { icon: 'G', color: 'text-blue-500 bg-blue-50 border-blue-100' },
  'gmail': { icon: 'M', color: 'text-rose-500 bg-rose-50 border-rose-100' },
  'youtube': { icon: 'Y', color: 'text-red-600 bg-red-50 border-red-100' },
  'facebook': { icon: 'F', color: 'text-blue-600 bg-blue-50 border-blue-100' },
  'instagram': { icon: 'I', color: 'text-fuchsia-600 bg-fuchsia-50 border-fuchsia-100' },
  'twitter': { icon: 'X', color: 'text-slate-900 bg-slate-100 border-slate-200' },
  'tiktok': { icon: 'tt', color: 'text-slate-900 bg-slate-100 border-slate-200' },
  'tinder': { icon: 't', color: 'text-rose-500 bg-rose-50 border-rose-100' },
  'amazon': { icon: 'a', color: 'text-orange-400 bg-orange-50 border-orange-100' },
  'apple': { icon: 'A', color: 'text-slate-800 bg-slate-100 border-slate-200' }
};

// Simple Icons brand icon mappings
export const simpleIconsMap: Record<string, string> = {
  'whatsapp': 'whatsapp',
  'telegram': 'telegram',
  'google': 'google',
  'gmail': 'gmail',
  'youtube': 'youtube',
  'facebook': 'facebook',
  'instagram': 'instagram',
  'twitter': 'x',
  'tiktok': 'tiktok',
  'tinder': 'tinder',
  'amazon': 'amazon',
  'apple': 'apple',
  'steam': 'steam',
  'netflix': 'netflix',
  'spotify': 'spotify',
  'discord': 'discord',
  'viber': 'viber',
  'vkontakte': 'vk',
  'microsoft': 'microsoft',
  'yahoo': 'yahoo',
  'wechat': 'wechat',
  'line': 'line',
  'signal': 'signal',
  'snapchat': 'snapchat',
  'reddit': 'reddit',
  'linkedin': 'linkedin',
  'airbnb': 'airbnb',
  'uber': 'uber',
  'zoom': 'zoom',
  'ebay': 'ebay',
  'paypal': 'paypal',
  'stripe': 'stripe',
  'slack': 'slack',
  'github': 'github',
  'gitlab': 'gitlab',
  // Extra mapping helpers for different database name variants
  'alibaba': 'alibabacom',
  'booking': 'bookingcom',
  'weibo': 'sinaweibo',
  'hbomax': 'max',
  'mercado': 'mercadolibre',
  'twitch': 'twitch'
};

// 5sim Country Code to ISO 3166-1 alpha-2 mapping
export const countryToIsoMap: Record<string, string> = {
  'russia': 'ru',
  'ukraine': 'ua',
  'kazakhstan': 'kz',
  'china': 'cn',
  'philippines': 'ph',
  'myanmar': 'mm',
  'indonesia': 'id',
  'malaysia': 'my',
  'kenya': 'ke',
  'vietnam': 'vn',
  'kyrgyzstan': 'kg',
  'usa': 'us',
  'unitedstates': 'us',
  'england': 'gb',
  'unitedkingdom': 'gb',
  'poland': 'pl',
  'germany': 'de',
  'france': 'fr',
  'spain': 'es',
  'italy': 'it',
  'netherlands': 'nl',
  'argentina': 'ar',
  'brazil': 'br',
  'colombia': 'co',
  'mexico': 'mx',
  'india': 'in',
  'turkey': 'tr',
  'turkiye': 'tr',
  'azerbaijan': 'az',
  'romania': 'ro',
  'bulgaria': 'bg',
  'greece': 'gr',
  'canada': 'ca',
  'australia': 'au',
  'egypt': 'eg',
  'morocco': 'ma',
  'thailand': 'th',
  'singapore': 'sg',
  'hongkong': 'hk',
  'taiwan': 'tw',
  'japan': 'jp',
  'korea': 'kr',
  'southkorea': 'kr',
  'portugal': 'pt',
  'sweden': 'se',
  'norway': 'no',
  'finland': 'fi',
  'denmark': 'dk',
  'switzerland': 'ch',
  'austria': 'at',
  'belgium': 'be',
  'ireland': 'ie',
  'southafrica': 'za',
  'nigeria': 'ng',
  'saudiarabia': 'sa',
  'uae': 'ae',
  'unitedarabemirates': 'ae',
  'israel': 'il',
  'pakistan': 'pk',
  'bangladesh': 'bd',
  'uzbekistan': 'uz',
  'tajikistan': 'tj',
  'turkmenistan': 'tm',
  'georgia': 'ge',
  'armenia': 'am',
  'moldova': 'md',
  'estonia': 'ee',
  'latvia': 'lv',
  'lithuania': 'lt',
  'belarus': 'by',
  'cyprus': 'cy',
  'cambodia': 'kh',
  'laos': 'la',
  'mongolia': 'mn',
  'nepal': 'np',
  'srilanka': 'lk',
  'chile': 'cl',
  'peru': 'pe',
  'venezuela': 've',
  'ecuador': 'ec',
  'bolivia': 'bo',
  'paraguay': 'py',
  'uruguay': 'uy',
  'algeria': 'dz',
  'tunisia': 'tn',
  'libya': 'ly',
  'iraq': 'iq',
  'jordan': 'jo',
  'lebanon': 'lb',
  'yemen': 'ye',
  'oman': 'om',
  'qatar': 'qa',
  'kuwait': 'kw',
  'bahrain': 'bh',
  // Extra Synced Countries from 5sim
  'afghanistan': 'af',
  'albania': 'al',
  'angola': 'ao',
  'antiguaandbarbuda': 'ag',
  'aruba': 'aw',
  'bahamas': 'bs',
  'barbados': 'bb',
  'belize': 'bz',
  'benin': 'bj',
  'bhutane': 'bt',
  'bih': 'ba',
  'botswana': 'bw',
  'burkinafaso': 'bf',
  'burundi': 'bi',
  'cameroon': 'cm',
  'capeverde': 'cv',
  'chad': 'td',
  'comoros': 'km',
  'congo': 'cg',
  'costarica': 'cr',
  'croatia': 'hr',
  'czech': 'cz',
  'djibouti': 'dj',
  'dominicana': 'do',
  'easttimor': 'tl',
  'equatorialguinea': 'gq',
  'ethiopia': 'et',
  'frenchguiana': 'gf',
  'gabon': 'ga',
  'gambia': 'gm',
  'ghana': 'gh',
  'guadeloupe': 'gp',
  'guatemala': 'gt',
  'guinea': 'gn',
  'guineabissau': 'gw',
  'guyana': 'gy',
  'haiti': 'ht',
  'honduras': 'hn',
  'hungary': 'hu',
  'ivorycoast': 'ci',
  'jamaica': 'jm',
  'lesotho': 'ls',
  'liberia': 'lr',
  'luxembourg': 'lu',
  'macau': 'mo',
  'madagascar': 'mg',
  'malawi': 'mw',
  'maldives': 'mv',
  'mauritania': 'mr',
  'mauritius': 'mu',
  'montenegro': 'me',
  'mozambique': 'mz',
  'namibia': 'na',
  'newcaledonia': 'nc',
  'nicaragua': 'ni',
  'northmacedonia': 'mk',
  'panama': 'pa',
  'papuanewguinea': 'pg',
  'puertorico': 'pr',
  'reunion': 're',
  'rwanda': 'rw',
  'saintkittsandnevis': 'kn',
  'saintlucia': 'lc',
  'saintvincentandgrenadines': 'vc',
  'salvador': 'sv',
  'samoa': 'ws',
  'senegal': 'sn',
  'serbia': 'rs',
  'seychelles': 'sc',
  'sierraleone': 'sl',
  'slovakia': 'sk',
  'slovenia': 'si',
  'solomonislands': 'sb',
  'suriname': 'sr',
  'swaziland': 'sz',
  'tanzania': 'tz',
  'tit': 'tt',
  'togo': 'tg',
  'uganda': 'ug',
  'zambia': 'zm'
};

export const getSimpleIconUrl = (name: string) => {
  const cleanName = name.toLowerCase().trim();
  const slug = simpleIconsMap[cleanName] || cleanName;
  return `https://cdn.jsdelivr.net/npm/simple-icons@latest/icons/${slug}.svg`;
};

export const getCountryFlagCode = (code: string) => {
  if (!code) return 'tr';
  const clean = code.toLowerCase().replace(/[^a-z0-9]/g, '');
  return countryToIsoMap[clean] || 'tr';
};
